### ISSUE TITLE
Merge work with OHHTTPStubs

### ISSUE THREAD

**Issue by AliSoftware** [aerogear/aerogear-ios-httpstub#15]
This is a followup of the conversation started with @corinnekrych at dotSwift and the comments [on this issue on OHHTTPStubs repo](https://github.com/AliSoftware/OHHTTPStubs/issues/65#issuecomment-73363682)

---

Hi @cvasilak 

I haven't had time to look in details into your Swift implementation yet, but my idea in my proposition was mainly to see how we could reduce maintenance, especially to only have one codebase to maintain instead of having two different libraries (yours and mine) that do the same work with the same API.

The problem with having two different codebases and two independent implementations is (as explained by JP Simard at the dotSwift workshop on "wrapping your libs in Swift", BTW) that:

* New features introduced in one lib won't be available in the other one
* Bug fixes won't be mutualized
* If the API diverges with time, migration will be difficult for users

Currently, according to multiple users of `OHHTTPStubs`, my library works great in Swift directly (thanks to automatic bridging). In the near future, I even plan to annotate my methods with the new `__attribute__(nonnull)` and `__attribute__(nullable)` attributes of Swift 1.2 to have even better bridging. And anyway, we won't be able to code everything in Swift because there are some features (like swizzling on `NSURLSession`) that aren't available in Swift.

---

So my idea was more either to let users use `OHHTTPStubs` as is directly in their Swift code (that works well so far), or having a Swift **wrapper** if there is a need for a better tailored API for Swift that would take advantage of the specific features of Swift (optionals, etc), so that the Swift wrapper would only wrap calls to the original `OHHTTPStubs` codebase and we only keep one codebase to maintain, to make bug fixes onto and to add features to.

Of course in that scenario I could give you push access to `OHHTTPStubs` so you could directly work on it and add features if you need.

What do you think of this approach?

**Comment by corinnekrych** [comment]
Hello Olivier,

The proposal of merging efforts sounds interesting!
With @cvasilak we would love to participate and contribute back to the library. Working on AG libraries we have rule of 2 reviewers before merging. I really think having more reviewer/feedback would improve/help maintenance of the lib, don't hesitate to include us in your PR reviews if you wish.

I've started looking into how to use OHHTPStubs from our Swift lib directly. The default Obj-C bridging works fine.
- I've just bumped in an issue with cocoapods 0.36.0-beta2 which is fixed in master: https://github.com/CocoaPods/swift/issues/30 - we have to add use_frameworks! in Podfile
- minor CInt/Int casting needed

Here is a branch with this work in progress:
https://github.com/corinnekrych/aerogear-ios-oauth2-1/blob/using.OHHTTPStubs/Podfile
I'll track the effort in our JIRA ticket: 
https://issues.jboss.org/browse/AGIOS-402

Tomorrow i'll try Swift 1.2 and post more comments on it.
++
Corinne

**Comment by AliSoftware** [comment]
Thanks for your feedback!

I like the idea of having two reviewers per PR, especially if there are people external to the project who contributes and submit those PR (other people don't always have the same coding standards, code quality requirements, or don't always write Unit Tests, etc), but even for our PRs to make sure it's robust in all contexts where the lib is used.

FYI, my short-term roadmap on `OHHTTPStubs` regarding Swift is the following:

* Add a Swift project example in my repository (right next to the existing example in ObjC, even maybe the exact same example but entierly written in Swift) to demonstrate to users how to use OHHTTPStubs from a Swift project. _I see you did the same with your AeroGear branch somehow to test the feasibility already_ :)
* Maybe even add a Playground to the Swift Example workspace (annotated with the new rich text comments `//:`) to be easily used as a "Getting Started" tutorial, why not
* See if any annotation using `__attribute__(nonnull)`/`__attribute__(nullable)` is necessary to make a better Swift briding. If so, be careful to still make the app compatible with earlier versions of Xcode, as Swift 1.2 is still only in the Beta and a lot of people are not up-to-date yet (I already had the case when I added the `DESIGNATED_INITIALIZER` attribute macro to my code, which is actually still not completely fixed for earlier Xcode versions not having this macro in their SDK headers).
* Add a reference in the README telling that `OHHTTPStubs` is Swift-compatible and can be used from Swift painlessly (and explanations about using it from CocoaPods 0.36, using the `use_frameworks!` flag)

**Comment by corinnekrych** [comment]
Howdy,

Here is an update on AeroGear mailing list:
http://aerogear-dev.1069024.n5.nabble.com/aerogear-dev-AeroGearHttpStub-is-gone-long-live-OHHTTPStubs-td11016.html

OHHTTPStubs repo is using GH issues and PRs, I'll do further work using that mean.

Let me close this issue,
++
Corinne

**Comment by AliSoftware** [comment]
:+1: :dancer:
